version: '3.1'

services:

  mongo:
    image: docker.io/mongo:latest
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: phonebook
      MONGO_INITDB_ROOT_PASSWORD: phonebook-pass
    
    volumes:
      - type: volume
        source: mydata
        target: /data/db

  mongo-express:
    image: docker.io/mongo-express:latest
    restart: always
    links:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: phonebook
      ME_CONFIG_MONGODB_ADMINPASSWORD: phonebook-pass
      ME_CONFIG_MONGODB_URL: mongodb://phonebook:phonebook-pass@mongo:27017/

volumes:
  mydata:
