name: build and deploy
on: push
#this pipeline must build a docker image and deploy it on K8s cluster

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    container: "ubuntu:latest"
    steps:
      - name: Update Packages
        run: apt-get update -y
      - name: Install Docker
        run: apt-get install -y docker.io
      - name: Create Docker Image
        #run: docker build -t dupa:dupa ./
        run: ls -l