name: build and deploy
on: push
#this pipeline must build a docker image and deploy it on K8s cluster
env: 
  DOCKER_HUB_REPOSITORY: ${{ vars.DOCKER_HUB_REPOSITORY }}
  DOCKER_HUB_PASS: ${{ secrets.DOCKER_HUB_PASS }}
  DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_DEFAULT_REGION: eu-central-1
jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    container: "docker:latest"
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Build and push image
        run: sh pipeline_scripts/build.sh

  deploy:
    name: Deploy Docker Image
    runs-on: ubuntu-latest
    container: "docker.io/tponomarenko/docker_aws_kubectl:latest"
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
      - name: Deploy phonebook to k8s
        run: sh pipeline_scripts/deploy.sh